### PR TITLE
Windows Instructions!

### PR DESCRIPTION
**Pull request by mattferderer**
Awesome tool! I just set it up on Windows. I use Cmder (popular Windows terminal tool). Here's how I did it.

**What**: Windows terminal instructions

**Why**: Your readme asked for them. Windows people need love too!

**How**: In the Read me.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

Will add to contributors table in sub-sequential commit.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Cool! Thanks!

**Comment by kentcdodds** [comment]
Hey, would you be interested in implementing a fix for something I thought of today but haven't gotten around to?

I think we should run a git pull before making any changes. This is useful if there were changed to the git repo via github.com out something. Make sense? Should hopefully be straightforward.

**Comment by mattferderer** [comment]
Ya I could do that tomorrow.

Are you thinking just adding it to the beginning of `commitAndPush`?

```javascript
function commitAndPush(short, longLink, cwd) {
  const message = longLink ? `${short} -> ${longLink}` : 'format links'
  console.log(`committing: ${message}`)
  spawnSync('git', ['commit', '-am', message], {
    stdio: 'inherit',
    cwd,
  })
  console.log('pushing')
  spawnSync('git', ['push'], {stdio: 'inherit', cwd})
}
```

If there were merge conflicts, would you want it to stop & output an error?

**Comment by kentcdodds** [comment]
I was thinking we'd run the git pull first, before making changes to avoid merge conflicts.

**Comment by kentcdodds** [comment]
And if there was an error, we don't need to handle it ourselves. We'll just let the program exit normally and people can figure out what's wrong themselves

**Pull request merged**
