### PR TITLE
Fix a typo in README.md

### PR DESCRIPTION
**Pull request by ddbeck**
**What**: Fix a misspelling of "functions" in the fish shell instructions

**Why**: Copying and pasting the path doesn't work as you might expect

**How**: With the backspace and `i` keys 😃 

**Checklist**:

- [X] Documentation
- [ ] Tests N/A
- [X] Ready to be merged 
- [ ] Added myself to contributors table N/A 

Thanks for this project. Very handy!

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by j-f1** [comment]
Sorry about that!

**Comment by kentcdodds** [comment]
No worries :)

**Comment by kentcdodds** [comment]
@all-contributors, please add @ddbeck for docs

**Pull request merged**
