### PR TITLE
Remove ambiguous characters from auto-generated shortcodes

### PR DESCRIPTION
**Pull request by jakejarvis**
Hi there! Feel free to reject if this is too opinionated but I think this could be a valuable improvement in general.

**What**:

Removed the following from the `possible` string of characters:

```
l, I, 1, O, 0
```

**Why**:

These can cause confusion when re-typing a shortcode being read from print, especially with some fonts.

http://example.com/OlI01 — `http://example.com/OlI01`

Inspired by the ["Avoid Ambiguous Characters"](https://discussions.agilebits.com/discussion/13143/ambiguous-characters) setting in the password generation feature of 1Password.

**How**:

Modified `possible` alphanumeric string in `utils.js`.

**Checklist**:

- [ ] Documentation (N/A)
- [ ] Tests (N/A)
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
I'm good with this. I personally rarely (never?) use this feature anyway. Thanks!

**Comment by kentcdodds** [comment]
I gotta do a tooling upgrade for this repo. I'll get to this as soon as I can. Sorry for the delay.

**Comment by jakejarvis** [comment]
No need to apologize, this has been working great for me! Thanks! :)

**Comment by kentcdodds** [comment]
@all-contributors please add @jakejarvis for code

**Pull request merged**
